---
title: "Simulation"
author: "Xinrui Shi"
date: "2023-05-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# import packages
library(dplyr)
library(ggplot2)
library(MASS)
library(Rcpp)

# set seed
set.seed(123)

# call functions
source("main_functions.R")
sourceCpp("pred_step.cpp")
sourceCpp("update_step.cpp")
sourceCpp("predKF.cpp")
```

# Simulated state-space model

```{r}
# initialize
gamma <- 1
phi <- exp(-1/gamma)
sigma.v <- sqrt(1- exp(-2/gamma))

sigma.w <- 1
n <- 3e2

# simulate state models
y <- sim_Xt(0, n, gamma)[-1] + rnorm(n, 0, sigma.w)
```

## Hyper-parameter selection



```{r}
# initialize
m0 <- 0
sigma0 <- 1

# observed length
T <- 200

hyperparam_hat <- optim_parm(y[1:T], m0, sigma0)
gamma <- hyperparam_hat$gamma
sigma.w <- hyperparam_hat$sigma.w
hyperparam_hat
```


```{r}
loglikelihood.partial(y[1:T], gamma, sigma.w, m0, sigma0)
```

## KF inference

```{r}
# KF inference
KF.inference <- gp.KF(y, gamma, sigma.w, m0, sigma0)

tt.record <- KF.inference$tt
t1t.record <- KF.inference$t1t
```

## Smoothing under KF 

```{r}
alpha <- 0.01
smooth.record <- smooth.KF(n, tt.record, t1t.record, alpha)
```


```{r}

plot(1:n, y, col="#56B4E9", pch=15, ylim=c(min(y)-2.5, max(y)+0.5),
       main = "Smoothing under KF", xlab="time", ylab="value")
points(smooth.record$t, smooth.record$m, col="#E69F00", pch=16)
lines(smooth.record$t, smooth.record$upper, col="#D55E00", lty=2)
lines(smooth.record$t, smooth.record$lower, col="#D55E00", lty=2)
legend("bottomleft", legend = c("observation", "smoothing mean","99% credible interval"), 
       pch = c(15, 16,NA ), 
       lty = c(NA, NA, 2),
       col=c("#56B4E9","#E69F00","#D55E00"))
```

## Prediction under KF

```{r}
# predict the next future time series
last.smooth <- tt.record %>% filter(t==n)

pred.record <- predKF(m_nn = last.smooth$m, 
                      sd_nn = last.smooth$sigma, 
                      gamma = gamma)


pred.sd <- sqrt(t1t.record$sigma^2 + sigma.w^2)
t1t.upper <- qnorm(1-alpha/2, mean=t1t.record$m, sd=pred.sd )
t1t.lower <- qnorm(alpha/2, mean=t1t.record$m, sd=pred.sd )
```


```{r}
plot(1:n, y, col="#56B4E9", pch=15,
     main = "Prediction under KF", 
     xlab="time", ylab="value", 
     xlim=c(0,n+2), ylim=c(min(y)-2.5, max(y)+0.5))
points(t1t.record$t, t1t.record$m, col="#E69F00", pch=16)
lines(t1t.record$t, t1t.upper, col="#D55E00", lty=2)
lines(t1t.record$t, t1t.lower, col="#D55E00", lty=2)
legend("bottomleft", legend = c("observation", "prediction mean",
                                "99% credible interval"), 
       pch = c(15, 16, NA), 
       lty = c(NA, NA, 2),
       col=c("#56B4E9","#E69F00","#D55E00"))
```






