---
title: "RW_test_code"
author: "Sam Perren"
date: "2023-06-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(MASS)
library(Rcpp)
library(readxl)
set.seed(123)

```

```{r data}
df <- read_excel("household_power_consumption_V2.xlsx")

#remove columns
dataset <- df[, c("Time", "Voltage")]
dataset$Voltage <- as.numeric(dataset$Voltage)
```

## Inference of GP using Kalman Filter

```{r}
# initialize
gamma <- 1
phi <- exp(-1/gamma)
sigma.v <- sqrt(1- exp(-2/gamma))

sigma.w <- 1

# Now we'll create a new dataset that only includes the first 100 rows

# Using head()
df_100_rows <- head(dataset, 100)

n <- 1e2 # Note here we now have to get the length of the real data
```

## Hyper-parameter selection

```{r}
# Assuming `df` is your data frame and `column_name` is the column to normalize
min_value <- min(df_100_rows$Voltage, na.rm = TRUE)  # get minimum value, ignoring NA values
max_value <- max(df_100_rows$Voltage, na.rm = TRUE)  # get maximum value, ignoring NA values

# create new normalized column
df_100_rows$normalized_column_name <- (df_100_rows$Voltage - min_value) / (max_value - min_value)

# Use your real-world 'Voltage' data instead of the synthetic data
y <- df_100_rows$normalized_column_name

# initialize
m0 <- 0
sigma0 <- 1

hyperparam_hat <- optim_parm(y, m0, sigma0)
gamma <- hyperparam_hat$gamma
sigma.w <- hyperparam_hat$sigma.w

```


```{r}
loglikelihood.partial(gamma, sigma.w)
```

## KF inference

```{r}
# KF inference
KF.inference <- gp.KF(y, gamma, sigma.w, m0, sigma0)

tt.record <- KF.inference$tt
t1t.record <- KF.inference$t1t
```

## Smoothing under KF 

```{r}
alpha <- 0.01
smooth.record <- smooth.KF(n, tt.record, t1t.record, alpha)
```


```{r}
plot(1:n, y, col="#56B4E9", pch=15, ylim=c(min(y)-0.5, max(y)+0.5),
       main = "Smoothing under KF", xlab="time", ylab="value")
points(smooth.record$t, smooth.record$m, col="#E69F00", pch=16)
lines(smooth.record$t, smooth.record$upper, col="#D55E00", lty=2)
lines(smooth.record$t, smooth.record$lower, col="#D55E00", lty=2)
legend("bottomleft", legend = c("observation", "smoothing mean","99% credible interval"), 
       pch = c(15, 16,NA ), 
       lty = c(NA, NA, 2),
       col=c("#56B4E9","#E69F00","#D55E00"))
```

## Prediction under KF

```{r}
# predict the next future time series
last.smooth <- tt.record %>% filter(t==n)

# Source the C++ file
sourceCpp("predKF.cpp")
pred.record <- predKF(last.smooth$m, last.smooth$sigma, gamma)
```


```{r}
plot(1:n, y, col="#56B4E9", pch=15,
     main = "Smoothing and prediction under KF", 
     xlab="time", ylab="value", 
     xlim=c(0,n+2), ylim=c(min(y)-0.5, max(y)+0.5))
points(smooth.record$t, smooth.record$m, col="#E69F00", pch=16)
points(n+1, pred.record$m, pch=17, col="red")
lines(smooth.record$t, smooth.record$upper, col="#D55E00", lty=2)
lines(smooth.record$t, smooth.record$lower, col="#D55E00", lty=2)
legend("bottomleft", legend = c("observation", "smoothing mean",
                                "99% credible interval", "predicted point"), 
       pch = c(15, 16, NA, 17 ), 
       lty = c(NA, NA, 2, NA),
       col=c("#56B4E9","#E69F00","#D55E00","red"))
```
## Using Rcpp


```{r warning=FALSE}

library(Rcpp)
sourceCpp("pred_step.cpp")
sourceCpp("update_step.cpp")
sourceCpp("predKF.cpp")
```

```{r}
gp.KF <- function(y, gamma, sigma.w, m0, sigma0){
  
  # compute the parameters
  phi <- exp(-1/gamma)
  sigma.v <- sqrt(1- exp(-2/gamma))
  
  # length of y
  n <- length(y)
  
  # record parameters m_{t|t}, sigma_{t|t}, m{t+1|t}, sigma_{t+1|t}
  tt.record <- data.frame(t = NULL, m = NULL, sigma = NULL)
  t1t.record <- data.frame(t = NULL, m = NULL, sigma = NULL)
  
  
  m1 <- sigma0^2*(y[1]-m0)/(sigma0^2+sigma.w^2)
  sigma1 <- sqrt(sigma0^2 - sigma0^4/(sigma0^2+sigma.w^2))
  
  tt.record1 <- data.frame(t = 1, m = m1, sigma = sigma1)
  tt.record <- rbind(tt.record, tt.record1)
  
  for(t in 1:(n-1)){
    # prediction step
    pred.param <- pred_step(m_tt = m1, 
                            sigma_tt = sigma1, 
                            phi = phi, 
                            sigma_v = sigma.v)
    m0 <- pred.param$m
    sigma0 <- pred.param$sigma
    t1t.record.i <- data.frame(t = t, m = m0, sigma = sigma0)
    t1t.record <- rbind(t1t.record, t1t.record.i)
    
    # updating step
    update.param <-     update_step(m_t1t = m0, 
                                    sigma_t1t = sigma0, 
                                    phi = phi, 
                                    sigma_w = sigma.w, 
                                    new_y = y[t+1])
    m1 <- update.param$m
    sigma1 <- update.param$sigma
    tt.record.i <- data.frame(t = t+1, m = m1, sigma = sigma1)
    tt.record <- rbind(tt.record, tt.record.i)
  }
  # prediction step at t=n
  pred.param <- pred_step(m_tt = m1, 
                          sigma_tt = sigma1, 
                          phi = phi, 
                          sigma_v = sigma.v)
  m0 <- pred.param$m
  sigma0 <- pred.param$sigma
  t1t.record.n <- data.frame(t = n, m = m0, sigma = sigma0)
  t1t.record <- rbind(t1t.record, t1t.record.n)
  
  return(list(tt=tt.record, t1t=t1t.record))
}
```

```{r}
# predict the next future time series
last.smooth <- tt.record %>% filter(t==n)

pred.record <- predKF(m_nn = last.smooth$m, 
                      sd_nn = last.smooth$sigma, 
                      gamma = gamma)
```
